# Etapa 1 - construir o frontend
FROM node:18-alpine AS builder

WORKDIR /app

# Copia o frontend para o build
COPY ../frontend ./frontend

WORKDIR /app/frontend
RUN npm install
RUN npm run build

# Etapa 2 - montar a imagem do backend com o build embutido
FROM node:18-alpine

WORKDIR /app

COPY backend/package*.json ./
RUN npm install

COPY backend/ ./

# Copiar o build do frontend da etapa anterior
COPY --from=builder /app/frontend/build ./client

RUN npm run build

CMD ["node", "dist/main.js"]
